Added nameToHex method
mexitek/phpColors pull request #55
Opened 2020-11-01 04:04 UTC by Braunson

As per #36

2020-11-01 04:13 UTC, Braunson commented
Mind adding the `hacktoberfest` topic on the repo OR add this tag on this issue `hacktoberfest-accepted` so it counts :)

2020-11-01 12:39 UTC, peter279k commented
If possible, could you add the tests for this `nameToHex` method?

2020-11-02 22:32 UTC, Braunson commented
@peter279k Yep, they've been added.

2020-11-03 07:05 UTC, mikaykun requested changes

2020-11-03 07:05 UTC, mikaykun commented on src/Mexitek/PHPColors/Color.php
> +            return ('#' . $colors[$color_name]);
Please remove unnecessary parentheses.
```suggestion
            return '#' . $colors[$color_name];
```

2020-11-03 07:05 UTC, mikaykun commented on src/Mexitek/PHPColors/Color.php
> +        return ($color_name);
Please remove unnecessary parentheses.
```suggestion
        return $color_name;
```

2020-11-03 07:07 UTC, mikaykun commented on tests/colorConvertHex.phpt
> +    $hex = '#'. $hex;
```suggestion
    $hex = '#' . $hex;
```

2020-11-03 08:47 UTC, peter279k commented
After checking the latest Travis CI build log, it will present the coding style issue via `vendor/bin/phpcs --extensions=php,phpt --warning-severity=0` command:

```
$ vendor/bin/phpcs --extensions=php,phpt --warning-severity=0

FILE: /home/travis/build/mexitek/phpColors/tests/colorConvertHex.phpt

----------------------------------------------------------------------

FOUND 1 ERROR AFFECTING 1 LINE

----------------------------------------------------------------------

 160 | ERROR | [x] Expected at least 1 space before "."; 0 found

----------------------------------------------------------------------

PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY

----------------------------------------------------------------------
```

2020-11-04 17:45 UTC, peter279k commented on README.md
> +- [Braunson](https://github.com/braunson)
To be consistency, I think it should be `braunson` without link sytntax.

2020-11-05 05:28 UTC, peter279k commented
@mikaykun, do you have any requested changes?

If not, I think we're going to be merged :).

2020-11-05 05:50 UTC, mikaykun approved these changes
@peter279k Looks good

2020-11-05 06:04 UTC, merged